mutation SubmitVote($token: String!, $nomineeid: Int!) {
  submitVote(input: { token: $token, nomineeId: $nomineeid }) {
    vote {
      id
      nominee {
        name
        id
      }
      date
    }
    errors
  }
}
